# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 14:56
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('validade', models.CharField(max_length=10)),
                ('codigo_seg', models.IntegerField()),
                ('nome_abv', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField()),
                ('historico', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='ContaUsuario',
            fields=[
                ('numero_conta', models.IntegerField(primary_key=True, serialize=False)),
                ('senha', models.IntegerField()),
                ('corrente_ativa', models.BooleanField()),
                ('poupanca_ativa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('cpf', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContaCorrente',
            fields=[
                ('contas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bancu.Contas')),
            ],
            bases=('bancu.contas',),
        ),
        migrations.CreateModel(
            name='Poupanca',
            fields=[
                ('contas_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bancu.Contas')),
            ],
            bases=('bancu.contas',),
        ),
        migrations.AddField(
            model_name='contausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancu.Usuario'),
        ),
        migrations.AddField(
            model_name='contas',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancu.ContaUsuario'),
        ),
        migrations.AddField(
            model_name='cartao',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bancu.ContaUsuario'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='contas',
            field=models.ManyToManyField(to='bancu.ContaUsuario'),
        ),
    ]
